Dev
monstrillllo/ppvis1 pull request #1
Opened 2020-04-27 13:03 UTC by monstrillllo

2020-05-03 12:59 UTC, Paulbel requested changes
Исправить замечания и прислать демо работы приложения

2020-05-03 12:59 UTC, Paulbel commented on src/com/company/GroupFive.java
> +public class GroupFive extends JPanel {
Назвать группы по функционалу

2020-05-03 12:59 UTC, Paulbel commented on src/com/company/GroupFour.java
> +            }
code style

2020-05-06 12:11 UTC, monstrillllo commented on src/com/company/GroupFour.java
> +            }
@Paulbel не могли бы вы пояснить  ?

2020-05-11 11:07 UTC, Paulbel approved these changes

2020-05-11 11:22 UTC, merged